import type { DocumentRecord } from "../types";

export const demoDocuments: DocumentRecord[] = [
  {
    id: "d1",
    fileName: "Audited Financials FY2023.pdf",
    category: "Financial Statements",
    linkedSection: "Restated Financial Statements",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-18",
    confidence: 94,
    extractedSummary: "Audited standalone financials for FY2023. Revenue ₹31.5 Cr, PAT ₹1.8 Cr, unqualified audit opinion.",
    keyEntities: ["Shakti Precision Components Pvt Ltd", "M/s Mehta & Associates (Auditor)"],
    keyNumbers: ["Revenue ₹31.5 Cr", "PAT ₹1.8 Cr", "Net Worth ₹9.2 Cr"],
  },
  {
    id: "d2",
    fileName: "Audited Financials FY2024.pdf",
    category: "Financial Statements",
    linkedSection: "Restated Financial Statements",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-18",
    confidence: 95,
    extractedSummary: "Audited standalone financials for FY2024. Revenue ₹38.7 Cr, PAT ₹2.4 Cr, unqualified audit opinion.",
    keyEntities: ["Shakti Precision Components Pvt Ltd", "M/s Mehta & Associates (Auditor)"],
    keyNumbers: ["Revenue ₹38.7 Cr", "PAT ₹2.4 Cr", "Net Worth ₹11.6 Cr"],
  },
  {
    id: "d3",
    fileName: "Audited Financials FY2025.pdf",
    category: "Financial Statements",
    linkedSection: "Restated Financial Statements",
    status: "Needs Review",
    issuesFound: ["Receivables grew 72% vs revenue growth of 35% — explanation required"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-20",
    confidence: 92,
    extractedSummary: "Audited standalone financials for FY2025. Revenue ₹52.4 Cr, PAT ₹3.2 Cr. Trade receivables ₹10.7 Cr (up 72% YoY).",
    keyEntities: ["Shakti Precision Components Pvt Ltd", "M/s Mehta & Associates (Auditor)"],
    keyNumbers: ["Revenue ₹52.4 Cr", "PAT ₹3.2 Cr", "Receivables ₹10.7 Cr", "Borrowings ₹11.8 Cr"],
  },
  {
    id: "d4",
    fileName: "GST Summary FY2025.pdf",
    category: "Tax Returns",
    linkedSection: "Financial Information",
    status: "Inconsistent",
    issuesFound: ["GST turnover ₹51.1 Cr vs audited revenue ₹52.4 Cr — reconciliation note needed"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-21",
    confidence: 88,
    extractedSummary: "GSTR-9 annual summary FY2025. Reported taxable turnover ₹51.1 Cr.",
    keyEntities: ["GSTIN 24AABCS1234F1Z5"],
    keyNumbers: ["GST Turnover ₹51.1 Cr"],
  },
  {
    id: "d5",
    fileName: "Bank Statement FY2025.pdf",
    category: "Banking",
    linkedSection: "Financial Information",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-21",
    confidence: 90,
    extractedSummary: "Consolidated current-account statement FY2025, HDFC Bank. Average utilisation of CC limit at 84%.",
    keyEntities: ["HDFC Bank, Rajkot Branch"],
    keyNumbers: ["CC Limit ₹9.0 Cr", "Avg Utilisation 84%"],
  },
  {
    id: "d6",
    fileName: "Board Resolution IPO.pdf",
    category: "Corporate Approvals",
    linkedSection: "General Information",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-22",
    confidence: 96,
    extractedSummary: "Board resolution dated 12-May-2026 approving IPO of up to ₹32 Cr and authorising promoter to appoint intermediaries.",
    keyEntities: ["Board of Directors", "Rajesh Patel (Chairman)"],
    keyNumbers: ["Issue size up to ₹32 Cr"],
  },
  {
    id: "d7",
    fileName: "Promoter KYC.pdf",
    category: "KYC",
    linkedSection: "Promoters and Promoter Group",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-22",
    confidence: 97,
    extractedSummary: "PAN, DIN and address proof of promoter Rajesh Patel. DIN 06712345 active, no disqualification flag.",
    keyEntities: ["Rajesh Patel", "DIN 06712345"],
    keyNumbers: [],
  },
  {
    id: "d8",
    fileName: "Litigation Declaration.pdf",
    category: "Legal",
    linkedSection: "Outstanding Litigation",
    status: "Inconsistent",
    issuesFound: ["Declaration states NIL litigation, but GST demand notice of ₹18 lakh found in tax records"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-23",
    confidence: 85,
    extractedSummary: "Signed declaration stating no pending litigation. Conflicts with GST demand notice detected in GST Summary FY2025.",
    keyEntities: ["Rajesh Patel"],
    keyNumbers: ["Declared litigation: NIL"],
  },
  {
    id: "d9",
    fileName: "RPT Register FY2025.xlsx",
    category: "Related Party",
    linkedSection: "Related Party Transactions",
    status: "Needs Review",
    issuesFound: ["Purchases of ₹3.4 Cr from Patel Industrial Traders LLP need disclosure narrative and arm's-length justification"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-23",
    confidence: 89,
    extractedSummary: "Related party register FY2025. Purchases ₹3.4 Cr from Patel Industrial Traders LLP (promoter group entity).",
    keyEntities: ["Patel Industrial Traders LLP", "Rajesh Patel"],
    keyNumbers: ["RPT Purchases ₹3.4 Cr"],
  },
  {
    id: "d10",
    fileName: "Machinery Quotation.pdf",
    category: "Objects Evidence",
    linkedSection: "Objects of the Issue",
    status: "Needs Review",
    issuesFound: ["Vendor GSTIN missing on quotation — obtain revised quotation"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-24",
    confidence: 82,
    extractedSummary: "Quotation from Precision Machines GmbH (India) for 4 CNC machines, total ₹11.6 Cr plus taxes.",
    keyEntities: ["Precision Machines GmbH (India)"],
    keyNumbers: ["Quotation ₹11.6 Cr"],
  },
  {
    id: "d11",
    fileName: "Working Capital Assessment.pdf",
    category: "Objects Evidence",
    linkedSection: "Objects of the Issue",
    status: "Needs Review",
    issuesFound: ["Assessment lacks detailed month-wise basis for ₹8 Cr requirement"],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-24",
    confidence: 78,
    extractedSummary: "Internal working capital note projecting ₹8 Cr incremental requirement for FY2027 based on 90-day cycle.",
    keyEntities: [],
    keyNumbers: ["WC Requirement ₹8 Cr", "Cycle 90 days"],
  },
  {
    id: "d12",
    fileName: "Material Contracts.zip",
    category: "Contracts",
    linkedSection: "Material Contracts and Documents",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-25",
    confidence: 87,
    extractedSummary: "Supply agreements with 3 OEM customers and lease deed for Rajkot factory (expires 2031).",
    keyEntities: ["OEM Customer A", "OEM Customer B", "OEM Customer C"],
    keyNumbers: ["3 supply agreements", "Lease till 2031"],
  },
  {
    id: "d13",
    fileName: "MOA-AOA.pdf",
    category: "Constitutional",
    linkedSection: "History and Corporate Structure",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-17",
    confidence: 98,
    extractedSummary: "Memorandum and Articles of Association, amended 2024 to authorise public issue.",
    keyEntities: [],
    keyNumbers: ["Authorised capital ₹15 Cr"],
  },
  {
    id: "d14",
    fileName: "Certificate of Incorporation.pdf",
    category: "Constitutional",
    linkedSection: "History and Corporate Structure",
    status: "Complete",
    issuesFound: [],
    uploadedBy: "Rajesh Patel",
    lastUpdated: "2026-06-17",
    confidence: 99,
    extractedSummary: "Certificate of Incorporation dated 03-Mar-2014, ROC Gujarat.",
    keyEntities: ["ROC Gujarat"],
    keyNumbers: [],
  },
  {
    id: "d15",
    fileName: "Restated Financials (Peer Reviewed).pdf",
    category: "Financial Statements",
    linkedSection: "Restated Financial Statements",
    status: "Missing",
    issuesFound: ["Restated financials by peer-reviewed auditor not yet uploaded — mandatory for offer document"],
    uploadedBy: "—",
    lastUpdated: "—",
    confidence: 0,
    extractedSummary: "Not uploaded.",
    keyEntities: [],
    keyNumbers: [],
  },
  {
    id: "d16",
    fileName: "Independent Director Consents.pdf",
    category: "Governance",
    linkedSection: "Management",
    status: "Missing",
    issuesFound: ["Consent letters and disclosures of proposed independent directors not uploaded"],
    uploadedBy: "—",
    lastUpdated: "—",
    confidence: 0,
    extractedSummary: "Not uploaded.",
    keyEntities: [],
    keyNumbers: [],
  },
];
