/**
 * SME IPO Draft Prospectus blueprint — based on the standard structure of SME
 * Draft Prospectuses / RHPs filed on NSE Emerge and BSE SME.
 *
 * The STRUCTURE below is intentionally hardcoded (it is the standard offer
 * document skeleton). Company-specific CONTENT is never hardcoded — every
 * section is generated only from uploaded documents, extracted facts and the
 * promoter's own inputs, with placeholders where data is missing.
 */

export interface BlueprintSection {
  sectionId: string;
  sectionName: string;
  parentSection: string;
  purpose: string;
  requiredFacts: string[];   // canonical fact keys (see facts.ts) or profile:* keys
  helpfulFacts: string[];
  requiredDocumentTypes: string[]; // document categories
  draftingInstructions: string;
  validationRules: string[];
  riskWarnings: string[];
  professionalReviewRequired: boolean;
  canGenerateWithPartialData: boolean;
}

const S = (
  sectionId: string, sectionName: string, parentSection: string, purpose: string,
  requiredFacts: string[], helpfulFacts: string[], requiredDocumentTypes: string[],
  draftingInstructions: string,
  opts: Partial<Pick<BlueprintSection, "validationRules" | "riskWarnings" | "professionalReviewRequired" | "canGenerateWithPartialData">> = {}
): BlueprintSection => ({
  sectionId, sectionName, parentSection, purpose, requiredFacts, helpfulFacts,
  requiredDocumentTypes, draftingInstructions,
  validationRules: opts.validationRules ?? [],
  riskWarnings: opts.riskWarnings ?? [],
  professionalReviewRequired: opts.professionalReviewRequired ?? true,
  canGenerateWithPartialData: opts.canGenerateWithPartialData ?? true,
});

export const SME_PROSPECTUS_BLUEPRINT: BlueprintSection[] = [
  // ── Front Matter ──────────────────────────────────────────────────────────
  S("fm-1", "Cover Page", "Front Matter",
    "Identifies the issuer, issue size, exchanges and key notices on the cover.",
    ["profile:name", "profile:issueSizeCr", "profile:proposedListingExchange"], ["cin", "profile:registeredOffice"],
    ["Constitutional"],
    "State issuer name, CIN, registered office, issue size (fresh/OFS split), proposed exchange and the standard cover-page risk legend. No marketing language."),
  S("fm-2", "Issue Programme", "Front Matter",
    "Tentative issue open/close dates.",
    [], ["profile:issueSizeCr"], [],
    "Insert placeholder programme dates: issue opening and closing dates are finalised with the merchant banker and exchange.", { canGenerateWithPartialData: true }),
  S("fm-3", "Issuer's Absolute Responsibility", "Front Matter",
    "Standard statutory statement of issuer responsibility for the offer document.",
    ["profile:name"], [], [],
    "Reproduce the standard issuer's absolute responsibility clause referencing the issuer by name."),
  S("fm-4", "Listing Details", "Front Matter",
    "States the SME platform where listing is proposed.",
    ["profile:proposedListingExchange"], [], [],
    "State the proposed SME platform and that in-principle approval will be obtained."),
  S("fm-5", "General Risk Disclaimer", "Front Matter",
    "Standard general-risk legend for SME issues.",
    [], [], [],
    "Reproduce the standard general risk statement for SME issues, including the 'investment in equity involves risk' legend.", { professionalReviewRequired: false }),
  S("fm-6", "Lead Manager, Registrar and Market Maker", "Front Matter",
    "Names the intermediaries to the issue.",
    [], ["profile:merchantBanker"], [],
    "Insert placeholders: lead manager, registrar and market maker are appointed by the issuer; details completed on appointment."),
  S("fm-7", "Table of Contents", "Front Matter",
    "Navigation of the offer document.",
    [], [], [],
    "Generate the table of contents from the blueprint section list.", { professionalReviewRequired: false }),

  // ── Section I — General ──────────────────────────────────────────────────
  S("g-1", "Definitions and Abbreviations", "Section I — General",
    "Defines company-related, issue-related and technical terms used in the document.",
    ["profile:name"], ["profile:industry"], [],
    "Produce standard definition tables (company terms, issue terms, technical/industry terms) using the issuer's actual name and industry.", { professionalReviewRequired: false }),
  S("g-2", "Certain Conventions and Use of Financial Information", "Section I — General",
    "Explains financial-year convention, currency, rounding and data sources.",
    [], ["fy"], ["Financial Statements"],
    "State fiscal-year convention (April–March), ₹ crore presentation, rounding, and that financial data derives from restated statements.", { professionalReviewRequired: false }),
  S("g-3", "Forward Looking Statements", "Section I — General",
    "Standard safe-harbour language for forward-looking statements.",
    [], [], [],
    "Reproduce standard forward-looking statement language.", { professionalReviewRequired: false }),

  // ── Section II — Summary ─────────────────────────────────────────────────
  S("s-1", "Summary of Offer Document", "Section II — Summary",
    "One-page summary of business, financials, objects, litigation and risks.",
    ["profile:name", "profile:issueSizeCr"], ["revenueCr", "patCr", "objects:total"], ["Financial Statements"],
    "Summarise: who the issuer is, headline restated financials, the issue structure, objects, promoter, and pointers to risk factors and litigation."),
  S("s-2", "Summary of Industry", "Section II — Summary",
    "Brief industry positioning.",
    ["profile:industry"], [], ["Industry / Business Overview"],
    "Two short paragraphs on the industry from uploaded industry material; if none uploaded, insert placeholder."),
  S("s-3", "Summary of Business", "Section II — Summary",
    "Brief description of operations.",
    ["profile:name", "profile:industry"], ["leaseValidTill"], ["Contracts"],
    "Summarise what the company makes/does, where, and for whom — strictly from extracted facts."),
  S("s-4", "Summary of Financial Information", "Section II — Summary",
    "Key restated financial figures for reported years.",
    ["revenueCr", "patCr"], ["ebitdaCr", "netWorthCr", "borrowingsCr"], ["Financial Statements"],
    "Tabulate revenue, EBITDA, PAT, net worth and borrowings by year from extracted facts. Note restatement status.",
    { validationRules: ["Figures must match extracted facts exactly"] }),
  S("s-5", "Summary of Objects of the Issue", "Section II — Summary",
    "Table of proposed fund utilisation.",
    ["objects:total"], ["quotationAmountCr", "wcRequirementCr"], ["Objects Evidence"],
    "Summarise the objects table from the Objects Builder with amounts and evidence status."),
  S("s-6", "Summary of Outstanding Litigation", "Section II — Summary",
    "Snapshot of litigation position.",
    ["litigationDeclared"], ["demandNoticeCr"], ["Legal"],
    "Summarise litigation counts/amounts from extracted facts; flag any inconsistency between declaration and detected notices.",
    { riskWarnings: ["Undisclosed litigation is a material defect"] }),
  S("s-7", "Summary of Risk Factors", "Section II — Summary",
    "Pointer list of the top risk factors.",
    [], ["top3CustomerPct"], [],
    "List the top 5 company-specific risks derived by the rule engine."),

  // ── Section III — Risk Factors ───────────────────────────────────────────
  S("r-1", "Internal Risk Factors", "Section III — Risk Factors",
    "Company-specific operational and financial risks.",
    ["revenueCr"], ["receivablesCr", "borrowingsCr", "rptPurchasesCr", "profile:top3CustomerPct"], ["Financial Statements"],
    "Derive each risk from the issuer's own numbers (concentration %, receivable days, leverage, RPTs, litigation). Never use generic template risks without company data.",
    { riskWarnings: ["Generic risk factors are the most common rework cause"] }),
  S("r-2", "External Risk Factors", "Section III — Risk Factors",
    "Industry, regulatory and macro risks.",
    ["profile:industry"], [], [],
    "Standard external risks tailored to the stated industry (input costs, competition, regulation, macro)."),
  S("r-3", "Issue-related Risk Factors", "Section III — Risk Factors",
    "Risks specific to the issue and SME listing.",
    ["profile:issueSizeCr"], ["profile:ofsCr"], [],
    "Cover SME liquidity, market-making dependence, price discovery, OFS component if any."),
  S("r-4", "Company-specific AI-suggested Risk Factors", "Section III — Risk Factors",
    "Additional risks surfaced by the analysis engine.",
    [], [], [],
    "Convert open High/Critical gaps and rule failures into candidate risk factors, each marked for professional review."),

  // ── Section IV — Introduction ────────────────────────────────────────────
  S("i-1", "The Issue", "Section IV — Introduction",
    "Issue structure table.",
    ["profile:issueSizeCr", "profile:freshIssueCr"], ["profile:ofsCr"], ["Corporate Approvals"],
    "Present the issue table: fresh issue, OFS, pre/post-issue capital (placeholders where share counts unknown)."),
  S("i-2", "Summary Financial Information", "Section IV — Introduction",
    "Condensed restated financial statements.",
    ["revenueCr", "patCr", "netWorthCr"], ["cfoCr"], ["Financial Statements"],
    "Condensed balance sheet / P&L / cash-flow rows by year from extracted facts."),
  S("i-3", "General Information", "Section IV — Introduction",
    "Registered office, registration details, board composition, intermediaries.",
    ["profile:name", "cin"], ["din", "boardResolutionDate"], ["Constitutional", "Corporate Approvals"],
    "State CIN, registered office, incorporation details, board resolution authorising the issue, and intermediary placeholders."),
  S("i-4", "Capital Structure", "Section IV — Introduction",
    "Share capital history and issue impact.",
    ["authorisedCapitalCr"], ["profile:freshIssueCr"], ["Constitutional"],
    "Authorised/paid-up capital from MOA facts; capital build-up table placeholder; promoter contribution & lock-in statement.",
    { validationRules: ["Post-issue capital must respect SME thresholds"] }),
  S("i-5", "Objects of the Issue", "Section IV — Introduction",
    "Detailed fund utilisation, deployment schedule, means of finance.",
    ["objects:total"], ["quotationAmountCr", "wcRequirementCr", "promoterLoanCr"], ["Objects Evidence"],
    "Detail each object with amount, evidence (quotation/computation), deployment schedule, means of finance, monitoring. Flag unsupported amounts and related-party repayments.",
    { validationRules: ["Objects total ≈ fresh issue", "Capex needs quotation", "WC needs computation"], riskWarnings: ["Related-party loan repayment from proceeds attracts scrutiny"] }),
  S("i-6", "Basis for Issue Price", "Section IV — Introduction",
    "Quantitative justification of the price band.",
    ["patCr", "netWorthCr"], ["peer:data"], [],
    "Compute EPS, RoNW, NAV from facts. Peer comparison requires uploaded/manual peer data — insert placeholder if unavailable.",
    { validationRules: ["Peer set required for comparison"] }),
  S("i-7", "Statement of Tax Benefits", "Section IV — Introduction",
    "Auditor's statement of special tax benefits.",
    [], [], ["Tax Returns"],
    "Insert placeholder: statement of special tax benefits to be certified by the statutory auditor.", { canGenerateWithPartialData: true }),

  // ── Section V — About the Company ────────────────────────────────────────
  S("c-1", "Industry Overview", "Section V — About the Company",
    "The industry the issuer operates in.",
    ["profile:industry"], [], ["Industry / Business Overview"],
    "Use only uploaded industry material with citations; otherwise placeholder requiring an industry report."),
  S("c-2", "Our Business", "Section V — About the Company",
    "Detailed business description.",
    ["profile:name", "profile:industry"], ["leaseValidTill", "profile:top3CustomerPct"], ["Contracts"],
    "Describe products, facilities, customers, suppliers, capacity — each claim tied to an extracted fact or marked for promoter confirmation."),
  S("c-3", "Key Industry Regulations and Policies", "Section V — About the Company",
    "Regulatory framework applicable to the business.",
    ["profile:industry"], ["gstin"], ["Licenses & Approvals"],
    "List regulations evidenced by uploaded licenses plus standard framework for the industry."),
  S("c-4", "History and Certain Corporate Matters", "Section V — About the Company",
    "Incorporation, milestones, structure.",
    ["cin"], ["authorisedCapitalCr"], ["Constitutional"],
    "Incorporation details from COI/MOA facts; amendments; corporate structure."),
  S("c-5", "Our Management", "Section V — About the Company",
    "Board of directors and KMP.",
    ["profile:promoterName"], ["din"], ["KYC", "Governance"],
    "Board table from KYC/governance facts. Flag missing independent directors/committees explicitly.",
    { validationRules: ["Independent directors and committees required for listing"] }),
  S("c-6", "Corporate Governance", "Section V — About the Company",
    "Committees and governance compliance.",
    ["profile:auditCommitteeConstituted"], [], ["Governance"],
    "State committee constitution status from facts; list gaps as placeholders."),
  S("c-7", "Our Promoters and Promoter Group", "Section V — About the Company",
    "Promoter background and group entities.",
    ["profile:promoterName"], ["din", "pan", "rptEntityNames"], ["KYC"],
    "Promoter profile from KYC facts; promoter-group entities from RPT/entity facts; confirmation placeholder for completeness."),
  S("c-8", "Group Companies", "Section V — About the Company",
    "Group companies as applicable.",
    [], ["rptEntityNames"], ["Related Party"],
    "List group entities identified from records or state none identified pending promoter confirmation."),
  S("c-9", "Related Party Transactions", "Section V — About the Company",
    "Summary of RPTs with reference to restated statements.",
    ["rptPurchasesCr"], ["promoterLoanCr"], ["Related Party"],
    "Tabulate RPTs by year/counterparty from extracted facts; note arm's-length basis and approvals status.",
    { riskWarnings: ["Missing pricing justification is a standard exchange query"] }),
  S("c-10", "Dividend Policy", "Section V — About the Company",
    "Dividend history and policy.",
    [], [], ["Financial Statements"],
    "State dividend history from facts (or that no dividend was declared) and the standard policy statement.", { professionalReviewRequired: false }),

  // ── Section VI — Financial Information ───────────────────────────────────
  S("f-1", "Restated Financial Statements", "Section VI — Financial Information",
    "Restated financials with examination report.",
    ["restated:present"], ["revenueCr", "patCr"], ["Restated Financials"],
    "If restated statements are uploaded, reference them; otherwise placeholder: restated financials by peer-reviewed auditor REQUIRED.",
    { validationRules: ["Restated statements are mandatory"], canGenerateWithPartialData: true }),
  S("f-2", "Other Financial Information", "Section VI — Financial Information",
    "Accounting ratios: EPS, RoNW, NAV, debt-equity.",
    ["patCr", "netWorthCr"], ["borrowingsCr"], ["Financial Statements"],
    "Compute ratios strictly from extracted facts, showing formulae."),
  S("f-3", "Statement of Financial Indebtedness", "Section VI — Financial Information",
    "Borrowings summary.",
    ["borrowingsCr"], ["promoterLoanCr"], ["Banking"],
    "Tabulate borrowings from facts and sanction letters; flag related-party loans separately."),
  S("f-4", "Management's Discussion and Analysis", "Section VI — Financial Information",
    "MD&A of results and financial condition.",
    ["revenueCr", "patCr"], ["receivablesCr", "cfoCr"], ["Financial Statements"],
    "Discuss year-on-year movements using only extracted figures; explain flagged anomalies (receivable growth, cash-flow quality) or insert promoter-explanation placeholders."),
  S("f-5", "Capitalisation Statement", "Section VI — Financial Information",
    "Pre/post-issue capitalisation.",
    ["borrowingsCr", "netWorthCr"], ["profile:freshIssueCr"], ["Financial Statements"],
    "Pre-issue from facts; post-issue placeholders pending pricing."),
  S("f-6", "Accounting Ratios and KPIs", "Section VI — Financial Information",
    "KPI table.",
    ["revenueCr", "patCr"], ["ebitdaCr", "receivablesCr"], ["Financial Statements"],
    "KPI table (growth, margins, working-capital days, RoE) computed from facts only."),

  // ── Section VII — Legal and Other Information ────────────────────────────
  S("l-1", "Outstanding Litigation and Material Developments", "Section VII — Legal",
    "All litigation involving company, promoters, directors, group.",
    ["litigationDeclared"], ["demandNoticeCr"], ["Legal", "Tax Returns"],
    "List each matter from facts (forum, amount, status). Reconcile declaration against detected notices — flag contradictions as critical.",
    { riskWarnings: ["Declaration/notice mismatch must be resolved before filing"] }),
  S("l-2", "Government and Other Statutory Approvals", "Section VII — Legal",
    "Licenses and approvals held/pending.",
    ["gstin"], ["leaseValidTill"], ["Licenses & Approvals"],
    "List approvals from uploads with validity; placeholders for expiry dates not extracted."),
  S("l-3", "Other Regulatory and Statutory Disclosures", "Section VII — Legal",
    "Statutory disclosures: eligibility, authority for issue, no-prohibition statements.",
    ["boardResolutionDate"], [], ["Corporate Approvals"],
    "Authority for the issue from board/shareholder resolutions; standard no-debarment statements referencing KYC checks."),

  // ── Section VIII — Issue Related Information ─────────────────────────────
  S("x-1", "Terms of the Issue", "Section VIII — Issue Information",
    "Terms of the equity shares offered.",
    ["profile:issueSizeCr"], [], [],
    "Standard terms with issuer specifics; pricing placeholders."),
  S("x-2", "Issue Structure", "Section VIII — Issue Information",
    "Allocation structure (QIB/NII/Retail/Market Maker).",
    ["profile:issueSizeCr"], [], [],
    "Standard SME issue-structure table with market-maker reservation placeholder."),
  S("x-3", "Issue Procedure", "Section VIII — Issue Information",
    "Application and allotment process (ASBA/UPI).",
    [], [], [],
    "Standard SME issue procedure language.", { professionalReviewRequired: false }),
  S("x-4", "Restrictions on Foreign Ownership", "Section VIII — Issue Information",
    "FDI/FEMA restrictions as applicable.",
    ["profile:industry"], [], [],
    "Standard FEMA/FDI language noting sectoral caps for the stated industry."),
  S("x-5", "Market Making Arrangement", "Section VIII — Issue Information",
    "Mandatory SME market-making arrangement.",
    [], [], [],
    "Standard market-making obligations; market maker name placeholder."),
  S("x-6", "Basis of Allotment", "Section VIII — Issue Information",
    "Allotment methodology.",
    [], [], [],
    "Standard basis-of-allotment language.", { professionalReviewRequired: false }),
  S("x-7", "Utilisation of Issue Proceeds", "Section VIII — Issue Information",
    "Undertakings on use and monitoring of proceeds.",
    ["objects:total"], [], ["Objects Evidence"],
    "Undertakings tied to the actual objects table; interim-use and monitoring statements."),

  // ── Section IX / X ───────────────────────────────────────────────────────
  S("a-1", "Main Provisions of Articles of Association", "Section IX — AoA",
    "Key AoA provisions.",
    [], ["authorisedCapitalCr"], ["Constitutional"],
    "Summarise key provisions if AOA uploaded; otherwise placeholder requiring the AOA."),
  S("o-1", "Material Contracts and Documents for Inspection", "Section X — Other",
    "Contracts and documents available for inspection.",
    [], ["leaseValidTill"], ["Contracts"],
    "List material contracts from uploads plus standard inspection documents."),
  S("o-2", "Declaration", "Section X — Other",
    "Signed declaration of correctness.",
    ["profile:name", "profile:promoterName"], [], ["Corporate Approvals"],
    "Standard declaration in prescribed form, naming signatories, marked draft-for-review."),
];

/** Sections the on-screen generator prioritises (most substantive content). */
export const PRIORITY_SECTION_IDS = [
  "s-1", "s-4", "s-5", "s-6", "r-1", "i-1", "i-3", "i-4", "i-5", "i-6",
  "c-2", "c-5", "c-7", "c-9", "f-2", "f-3", "f-4", "f-6", "l-1", "l-2", "o-1", "o-2",
];

export function blueprintSection(sectionId: string): BlueprintSection | undefined {
  return SME_PROSPECTUS_BLUEPRINT.find((s) => s.sectionId === sectionId);
}
