import { NextResponse } from "next/server";
import { getContext } from "@/lib/server/context";

const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Draft Offer Document as printable HTML (print → Save as PDF). */
export async function GET() {
  const { company, draft } = getContext();
  const name = company?.name ?? "Company";
  const html = `<!doctype html><html><head><meta charset="utf-8">
<title>Draft Offer Document — ${esc(name)}</title>
<style>
  body{font-family:Georgia,'Times New Roman',serif;max-width:820px;margin:40px auto;padding:0 24px;color:#111;line-height:1.6}
  h1{font-size:26px;border-bottom:3px solid #1e3a5f;padding-bottom:12px}
  h2{font-size:19px;color:#1e3a5f;margin-top:36px;border-bottom:1px solid #cbd5e1;padding-bottom:6px}
  .banner{background:#fef3c7;border:1px solid #f59e0b;padding:12px 16px;border-radius:6px;font-size:13px;font-family:system-ui,sans-serif}
  .meta{color:#555;font-size:13px;font-family:system-ui,sans-serif}
  .src{background:#eff6ff;border-left:3px solid #2a78d6;padding:8px 12px;font-size:12.5px;font-family:system-ui,sans-serif;margin-top:10px}
  .warn{background:#fef2f2;border-left:3px solid #d03b3b;padding:8px 12px;font-size:12.5px;font-family:system-ui,sans-serif;margin-top:8px}
  p{white-space:pre-wrap}
  @media print {.noprint{display:none}}
</style></head><body>
<div class="banner"><b>DRAFT — AI-ASSISTED PREPARATION.</b> This document is generated by IPO Saathi for review by SEBI-registered merchant bankers and legal counsel. It is <b>not</b> an offer document, has <b>not</b> been filed with SEBI or any stock exchange, and must not be used to invite subscription. It does not constitute legal, investment, accounting or regulatory advice.</div>
<h1>Draft Offer Document<br><span style="font-size:18px">${esc(name)}</span></h1>
<p class="meta">Generated by IPO Saathi on ${new Date().toLocaleDateString("en-IN", { dateStyle: "long" })} · ${draft.length} sections · Status: prepared for merchant banker review</p>
<button class="noprint" onclick="print()" style="padding:8px 20px;background:#1e3a5f;color:#fff;border:0;border-radius:6px;cursor:pointer;font-size:14px">Print / Save as PDF</button>
${draft.map((s) => `
<h2>${esc(s.sectionName)}</h2>
<p class="meta">AI-generated · Confidence ${s.confidence}% · Status: ${esc(s.status)} · Needs professional review</p>
<p>${esc(s.generatedText)}</p>
${s.sources.length ? `<div class="src"><b>Source evidence:</b> ${s.sources.map((x) => `${esc(x.document)} (${esc(x.detail)})`).join(" · ")}</div>` : ""}
${s.missingData.length ? `<div class="warn"><b>Missing data:</b> ${s.missingData.map(esc).join(" · ")}</div>` : ""}
`).join("")}
<hr><p class="meta">© IPO Saathi — AI Disclosure Intelligence for SME IPOs. Draft preparation tool only; final responsibility rests with the issuer and its intermediaries.</p>
</body></html>`;
  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
