import { NextResponse } from "next/server";
import { getContext } from "@/lib/server/context";
import { SME_PROSPECTUS_BLUEPRINT } from "@/lib/ipo-blueprint/sme-prospectus-blueprint";
import { mdToHtml } from "@/lib/utils/markdown";

const esc = (s: string) =>
  (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/**
 * Draft Offer Document as printable HTML (print → Save as PDF).
 * Includes ONLY the sections that have been generated, in SME prospectus
 * blueprint order — each starting on a fresh page. Ungenerated sections are
 * omitted from the document (they remain tracked in the Coverage Matrix).
 */
export async function GET() {
  const { company, draft } = await getContext();
  const name = company?.name ?? "Company";
  const byName = new Map(draft.map((s) => [s.sectionName, s]));
  const included = SME_PROSPECTUS_BLUEPRINT.filter(
    (bp) => byName.has(bp.sectionName) && (byName.get(bp.sectionName)!.status !== "Not Started")
  );

  let lastParent = "";
  const body = included.map((bp) => {
    const s = byName.get(bp.sectionName)!;
    const partHeader = bp.parentSection !== lastParent
      ? `<h2 class="part">${esc((lastParent = bp.parentSection))}</h2>` : "";
    return `<section class="sec">
${partHeader}
<h3>${esc(bp.sectionName)}</h3>
<p class="meta">AI-generated · Confidence ${s.confidence}% · Status: ${esc(s.status)} · Needs professional review</p>
<div class="body">${mdToHtml(s.generatedText)}</div>
${s.sources.length ? `<div class="src"><b>Source evidence:</b> ${s.sources.map((x) => `${esc(x.document)} (${esc(x.detail)})`).join(" · ")}</div>` : ""}
</section>`;
  }).join("\n");

  const toc = (() => {
    let lp = "";
    return included.map((bp) => {
      const head = bp.parentSection !== lp ? `<li class="toc-part">${esc((lp = bp.parentSection))}</li>` : "";
      return `${head}<li>${esc(bp.sectionName)}</li>`;
    }).join("");
  })();

  const html = `<!doctype html><html><head><meta charset="utf-8">
<title>Draft Offer Document — ${esc(name)}</title>
<style>
  body{font-family:Georgia,'Times New Roman',serif;max-width:820px;margin:40px auto;padding:0 24px;color:#111;line-height:1.6}
  h1{font-size:26px;border-bottom:3px solid #1e3a5f;padding-bottom:12px}
  h2.part{font-size:15px;color:#fff;background:#1e3a5f;padding:6px 12px;border-radius:4px;margin-top:40px;font-family:system-ui,sans-serif;letter-spacing:.4px}
  h3{font-size:18px;color:#1e3a5f;margin-top:28px;border-bottom:1px solid #cbd5e1;padding-bottom:5px}
  .banner{background:#fef3c7;border:1px solid #f59e0b;padding:12px 16px;border-radius:6px;font-size:13px;font-family:system-ui,sans-serif}
  .meta{color:#555;font-size:12.5px;font-family:system-ui,sans-serif}
  .src{background:#eff6ff;border-left:3px solid #2a78d6;padding:8px 12px;font-size:12.5px;font-family:system-ui,sans-serif;margin-top:10px}
  .warn{background:#fef2f2;border-left:3px solid #d03b3b;padding:8px 12px;font-size:12.5px;font-family:system-ui,sans-serif;margin-top:8px}
  .todo{background:#f8fafc;border:1px dashed #94a3b8;padding:10px 14px;font-size:13px;font-family:system-ui,sans-serif;color:#475569;border-radius:6px}
  .toc{font-family:system-ui,sans-serif;font-size:13px;columns:2;margin:12px 0}
  .toc li{margin-left:18px} .toc-part{list-style:none;margin-left:0;font-weight:700;color:#1e3a5f;margin-top:6px}
  .pending{color:#94a3b8;font-size:11px}
  .body p{margin:.5em 0;text-align:justify}
  .body .md-h{font-family:system-ui,sans-serif;font-size:13.5px;color:#1e3a5f;margin:14px 0 4px;font-weight:700}
  .body ul.md-ul{margin:.4em 0;padding-left:1.4em}
  .body table.md-table{width:100%;border-collapse:collapse;margin:10px 0;font-size:12.5px;font-family:system-ui,sans-serif;page-break-inside:avoid}
  .body table.md-table th{background:#eef2f7;font-weight:600;text-align:left}
  .body table.md-table th,.body table.md-table td{border:1px solid #c7d0dc;padding:5px 9px}
  .body table.md-table tr:nth-child(even) td{background:#f7f9fb}
  .body table.md-table th.num,.body table.md-table td.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
  section.sec{page-break-before:always}
  h2.part{page-break-after:avoid;margin-top:0} h3{page-break-after:avoid}
  @media print {.noprint{display:none}}
</style></head><body>
<div class="banner"><b>DRAFT — AI-ASSISTED PREPARATION.</b> Generated by SIIM for review by SEBI-registered merchant bankers and legal counsel. Not an offer document, not filed with SEBI or any exchange, and must not be used to invite subscription. Not legal, investment, accounting or regulatory advice.</div>
<h1>Draft Offer Document<br><span style="font-size:18px">${esc(name)}</span></h1>
<p class="meta">Generated ${new Date().toLocaleDateString("en-IN", { dateStyle: "long" })} · ${included.length} drafted sections (blueprint order) · undrafted sections are tracked in the Coverage Matrix · Status: prepared for merchant banker review</p>
<button class="noprint" onclick="print()" style="padding:8px 20px;background:#1e3a5f;color:#fff;border:0;border-radius:6px;cursor:pointer;font-size:14px">Print / Save as PDF</button>
<h2 class="part">Table of Contents</h2>
<ul class="toc">${toc}</ul>
${body}
<hr><p class="meta">© SIIM — AI Disclosure Intelligence for SME IPOs. Draft preparation tool only; final responsibility rests with the issuer and its intermediaries.</p>
</body></html>`;
  return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
